version: '3.8'
services:
  api-production:
    image: "geoabbey/express-server:production"
    env_file:
     - .env-backend-production.txt
    labels:
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to$
      - "traefik.http.routers.api.rule=Host(`api.ismail.com.ng`)" # <== Setting the domain for the d$
      - "traefik.http.routers.api.service=api@internal" # <== Enabling the api to be a service to acce$
    restart: always
    networks:
      - production

  postgres-production:
    image: postgres:14-alpine
    env_file:
     - .env-pg-production.txt
    volumes:
      - "/docker/data/postgres-production:/var/lib/postgresql/data"
    ports:
     - "5432:5432"
    restart: always
    networks:
      - production

  mongodb-production:
    image: mongo:6.0.2-focal
    env_file:
     - .env-mongo-production.txt
    volumes:
      - "/docker/data/mongodb-production:/data/db"
    restart: always
    ports:
     - "27017:27017"
    networks:
      - production

  traefik:
    image: traefik:v2.0
    restart: always
    container_name: traefik
    ports:
      - "80:80" # <== http
      - "8080:8080" # <== :8080 is where the dashboard runs on
      - "443:443" # <== https
    command:
      - --api.insecure=true # <== Enabling insecure api, NOT RECOMMENDED FOR PRODUCTION
      - --api.dashboard=true # <== Enabling the dashboard to view services, middlewares, routers, etc.
      - --api.debug=true # <== Enabling additional endpoints for debugging and profiling
      - --log.level=DEBUG # <== Setting the level of the logs from traefik
      - --providers.docker=true # <== Enabling docker as the provider for traefik
      - --providers.docker.exposedbydefault=false # <== Don't expose every container to traefik
      - --providers.file.filename=/dynamic.yaml # <== Referring to a dynamic configuration file
      - --providers.docker.network=web # <== Operate on the docker network named web
      - --entrypoints.web.address=:80 # <== Defining an entrypoint for port :80 named web
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
      - ./dynamic.yaml:/dynamic.yaml # <== Volume for dynamic conf file, **ref: line 27
    networks:
      - production # <== Placing traefik on the network named web, to access containers on this network
    labels:
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to$
      - "traefik.http.routers.api.rule=Host(`monitor.ismail.com.ng`)" # <== Setting the domain for the d$
      - "traefik.http.routers.api.service=api@internal" # <== Enabling the api to be a service to acce$

networks:
  production:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"