name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build production container
      run: docker build . -t geoabbey/express-server:production --build-arg=NODE_ENV=production
      if: contains('refs/heads/main',github.ref)
    - name: Navigate to compose folder
      run: cat ~/docker/compose/docker-compose.yml
    - name: List everything inside
      run: ls
    - name: Reload containers
      run: docker compose -f ~/docker/compose/docker-compose.yml up -d