name: CI/CD

on:
  push:
    branches:
      - develop
      - release
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment
      env:
        ENVIRONMENT: ${{ if: eq(github.ref, 'refs/heads/develop'), then: 'development', else if: eq(github.ref, 'refs/heads/release'), then: 'staging', else: 'production' }}

    - name: Retrieve Secrets
      run: |
        echo "${{ secrets.ENVIRONMENT_SECRET }}" > ${GITHUB_WORKSPACE}/secret-${{ env.ENVIRONMENT }}.env

    - name: Build Docker image
      run: |
        docker build --build-arg env={{ env.ENVIRONMENT }} --build-arg-file=${GITHUB_WORKSPACE}/secret-${{ env.ENVIRONMENT }}.env -t aptresponse:${{ env.ENVIRONMENT }} .
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Push to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        export REPOSITORY=ghcr.io/${{ github.repository }}
        docker tag aptresponse:${{ env.ENVIRONMENT }} ${REPOSITORY}:${{ env.ENVIRONMENT }}
        docker push ${REPOSITORY}:${{ env.ENVIRONMENT }}
