name: CI/CD

on:
  push:
    branches:
      - develop
      - release
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set development environment
      if: endsWith(github.ref, 'develop')
      run: echo "ENVIRONMENT=development" >> $GITHUB_ENV
    - name: Set staging environment
      if: endsWith(github.ref, 'release')
      run: echo "ENVIRONMENT=staging" >> $GITHUB_ENV
    - name: Set production environment
      if: endsWith(github.ref, 'main')
      run: echo "ENVIRONMENT=production" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t express-starter-${{ env.ENVIRONMENT }}:latest .

    - id: repo
      uses: ASzc/change-string-case-action@v5
      with:
        string: ghcr.io/${{ github.repository }}

    - name: Push to GitHub Container Registry
      run: |
        echo "${{ secrets.GIT_DOCKER_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        export REPOSITORY=${{ steps.repo.outputs.lowercase }}
        docker tag express-starter-${{ env.ENVIRONMENT }}:latest ${REPOSITORY}-${{ env.ENVIRONMENT }}:latest
        docker push ${REPOSITORY}-${{ env.ENVIRONMENT }}:latest
